# frozen_string_literal: true

require 'faker'

# TODO: remove after the app is mature enough
class FakerRandomizer
  # TODO: add Faker::Markdown
  ALL = [
    Faker::Book.title,
    Faker::Books::Dune.quote,
    Faker::Books::Dune.saying,
    Faker::Coffee.blend_name,
    Faker::Fantasy::Tolkien.poem,
    Faker::Games::Dota.quote,
    Faker::Games::Fallout.quote,
    Faker::Games::Myst.quote,
    Faker::Games::Overwatch.quote,
    Faker::Movies::BackToTheFuture.quote,
    Faker::Movies::Departed.quote,
    Faker::Movies::Ghostbusters.quote,
    Faker::Movies::HarryPotter.quote,
    Faker::Movies::HitchhikersGuideToTheGalaxy.marvin_quote,
    Faker::Movies::HitchhikersGuideToTheGalaxy.quote,
    Faker::Movies::Hobbit.quote,
    Faker::Movies::Lebowski.quote,
    Faker::Movies::PrincessBride.quote,
    Faker::Movies::StarWars.quote,
    Faker::Movies::Tron.quote,
    Faker::Movies::VForVendetta.quote,
    Faker::Quote.famous_last_words,
    Faker::Quote.jack_handey,
    Faker::Quote.matz,
    Faker::Quote.most_interesting_man_in_the_world,
    Faker::Quote.robin,
    Faker::TvShows::AquaTeenHungerForce.quote,
    Faker::TvShows::BigBangTheory.quote,
    Faker::TvShows::BojackHorseman.quote,
    Faker::TvShows::BrooklynNineNine.quote,
    Faker::TvShows::Buffy.quote,
    Faker::TvShows::Buffy.episode,
    Faker::TvShows::Community.quotes,
    Faker::TvShows::DrWho.quote,
    Faker::TvShows::DumbAndDumber.quote,
    Faker::TvShows::FamilyGuy.quote,
    Faker::TvShows::FinalSpace.quote,
    Faker::TvShows::Friends.quote,
    Faker::TvShows::GameOfThrones.quote,
    Faker::TvShows::HeyArnold.quote,
    Faker::TvShows::HowIMetYourMother.quote,
    Faker::TvShows::MichaelScott.quote,
    Faker::TvShows::NewGirl.quote,
    Faker::TvShows::RickAndMorty.quote,
    Faker::TvShows::RuPaul.quote,
    Faker::TvShows::Seinfeld.quote,
    Faker::TvShows::SiliconValley.quote,
    Faker::TvShows::Simpsons.quote,
    Faker::TvShows::Stargate.quote,
    Faker::TvShows::StrangerThings.quote,
    Faker::TvShows::Suits.quote,
    Faker::TvShows::TheExpanse.quote,
    Faker::TvShows::TheFreshPrinceOfBelAir.quote,
    Faker::TvShows::TheITCrowd.quote,
    Faker::TvShows::TwinPeaks.quote,
    Faker::TvShows::VentureBros.quote
  ].shuffle
end
